[settings]
name = "Lua"
loadout_file = "loadout.toml"
root_dir = "."
run_command = ".venv\\Scripts\\python.exe main.py"
run_command_linux = "../venv/bin/python bot.py"
agent_id = "rlbot/VoidHC"
logo_file = ""

[details]
description = "Void's HC version (Test)"
fun_fact = "This is my first use of HC in a bot, the funny magic black box of ML is too slow"
source_link = "https://github.com/RLBot/python-example"
developer = "Crystall"
language = "Python"
tags = []
